### ISSUE TITLE
Revamp Registration UX

### ISSUE THREAD

**Issue by isaiahoh** [mac-ieee/IEEE-SB-Bot#9]
Currently Individuals are having difficulty joining a chapter, please change how they are able to join a chapter for example only need to react to a message to gain a role.

**Comment by ElectricEvan** [comment]
[ New Progress ]
Migrating to fork of discord.py (eg. pycord, nextcord) for better integration of buttons. This should allow the creation of a roles react page using the modern buttons UI. The main roles react page will list all the available chapters and the respective buttons, which, when clicked, will send a private embed of the chapter's description along with buttons to confirm or cancel the role assignment.

![image](https://user-images.githubusercontent.com/32850711/149448701-0116c10f-d925-44ba-84ac-b571dadca7e5.png)

**To-Do:**
- [ ] Add Embed message listing all chapters
- [ ] Send private mesage embed showing chapter description
- [ ] Confirm/cancel chapter join
- [ ] Edit private message to show a log chapters joined/resigned

**Issues:**
- [x] Fix interaction malfunction when bot restarts/reconnects to server
